# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - texlive-pictures
    - pdf2svg

# Build documentation in the correct directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

# The formats to build. NOTE: epub3 has some issues with "empty version", skip it for now.
formats:
  - pdf
  - htmlzip

# Make sure to build the [docs] extra so that we have the correct Python environment
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
